---
title: JBlog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Just a simple Jekyll theme
description: JBlog is a minimal, one column and blue jekyll theme for your blog.
picture: assets/img/profile.png
locale: en_US
url: https://alperenbozkurt.github.io/JBlog
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
twitter: username
facebook: username
github: username
stackoverflow: 
linkedin: username
instagram: username
lastfm: username
tumblr: username
steam: username
youtube: username
disqus_shortname: alperenbozkurt-net
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
