---
title: Kevin D. Looney
timezone: PST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Online Portfolio
description: Online portfolio and resume for Kevin D. Looney
picture: assets/img/illustratorpic.jpg
locale: en_US
url: http://www.kevindlooney.com
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
github: thelooneyest
linkedin: kevindlooney
instagram: klooney.design
disqus_shortname: kevindlooney.com
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
